plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - readme.md
theme: jekyll-theme-cayman
title: Belajar Vue Lifecycle
baseurl: "education-vue-lifecycle"
url: ""
